# Mode: just epaxos replication

mode:
  cc: none # concurrency control
  ab: epaxos # atomic broadcast
  read_only: occ
  batch: false
  retry: 20
  ongoing: 1 # per client

# Sites: 1 server, 5 replicas
site:
  server:
    - ["s101:8101", "s102:8102", "s103:8103"]
  client: # each line is a partition
    - ["c01"]

process:
  s101: localhost
  s102: localhost
  s103: localhost
  c01: localhost

host:
  localhost: 127.0.0.1
